# Generated by Django 4.0.1 on 2022-06-27 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blug',
            fields=[
                ('bgid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title here', max_length=80)),
                ('dt', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(default='name here', max_length=80)),
                ('desc', models.CharField(default='', max_length=3000)),
                ('head', models.CharField(default='', max_length=80)),
                ('chead', models.CharField(default='', max_length=3000)),
                ('head2', models.CharField(default='', max_length=80)),
                ('chead2', models.CharField(default='', max_length=3000)),
                ('imaz1', models.ImageField(default='', upload_to='ForBlog')),
                ('imaz2', models.ImageField(default='', upload_to='ForBlog')),
            ],
        ),
    ]
